/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Livro;
import model.DaoLivro;

/**
 *
 * @author aluno.lab
 */
public class LivroView extends javax.swing.JFrame {
    Livro livro;
    DaoLivro daoLivro;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LivroView.class.getName());

    /**
     * Creates new form LivroView
     */
    public LivroView() {
        initComponents();
        daoLivro = new DaoLivro();
        this.atualizarTabelaLivros();
    }

    public void atualizarTabelaLivros(){ 
        jTableLivro.setModel(new LivroTableModel(daoLivro.listarTodos())); 
    }
    
    public void limparCampos(){
        tfCodigo.setText("");
        tfNome.setText("");
        tfAutor.setText("");
        tfQtdPaginas.setText("");
        tfAnoLancamento.setText("");
        tfGenero.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFiltro = new javax.swing.ButtonGroup();
        labelTitulo = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        labelAutor = new javax.swing.JLabel();
        tfAutor = new javax.swing.JTextField();
        labelQtdPaginas = new javax.swing.JLabel();
        tfQtdPaginas = new javax.swing.JTextField();
        labelAnoLancamento = new javax.swing.JLabel();
        tfAnoLancamento = new javax.swing.JTextField();
        tfGenero = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivro = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        labelFiltro = new javax.swing.JLabel();
        rbGenero = new javax.swing.JRadioButton();
        rbAutor = new javax.swing.JRadioButton();
        tfFiltro = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();
        btnListaTodos = new javax.swing.JButton();
        rbTitulo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        labelTitulo.setText("Biblioteca");

        labelCodigo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelCodigo.setText("Código:");

        tfCodigo.setEnabled(false);

        labelNome.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelNome.setText("Nome:");
        labelNome.setToolTipText("");

        labelAutor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelAutor.setText("Autor:");

        labelQtdPaginas.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelQtdPaginas.setText("Páginas:");

        labelAnoLancamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelAnoLancamento.setText("Lançamento:");

        labelGenero.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelGenero.setText("Gênero:");

        jTableLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLivroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLivro);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        labelFiltro.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelFiltro.setText("Filtrar por:");

        bgFiltro.add(rbGenero);
        rbGenero.setText("Gênero");
        rbGenero.setToolTipText("");

        bgFiltro.add(rbAutor);
        rbAutor.setText("Autor");

        btnFiltro.setText("Filtrar");
        btnFiltro.addActionListener(this::btnFiltroActionPerformed);

        btnListaTodos.setText("Listar todos");
        btnListaTodos.setToolTipText("");
        btnListaTodos.addActionListener(this::btnListaTodosActionPerformed);

        bgFiltro.add(rbTitulo);
        rbTitulo.setText("Título");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNome)
                            .addComponent(tfAutor)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelAnoLancamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAnoLancamento))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelQtdPaginas)
                                    .addComponent(labelGenero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfQtdPaginas)
                                    .addComponent(tfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar)))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(257, 257, 257))))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbGenero)
                        .addGap(12, 12, 12)
                        .addComponent(rbAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListaTodos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnoLancamento)
                    .addComponent(tfAnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelQtdPaginas)
                        .addComponent(tfQtdPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAutor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelGenero)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFiltro)
                    .addComponent(rbGenero)
                    .addComponent(rbAutor)
                    .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltro)
                    .addComponent(btnListaTodos)
                    .addComponent(rbTitulo))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //exibe uma msg na tela avisando que há campos não preenchidos
        if(tfNome.getText(). equals("") || tfAutor.getText().equals("") ||
           tfQtdPaginas.getText().equals("") || tfAnoLancamento.getText().equals("") ||
           tfGenero.getText().equals("")){ 
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "AVISO", JOptionPane.WARNING_MESSAGE);
        }else{
            // quando o botão for clicado e todos os  campos estão preenchidos, 
            // define as as informações e salva no banco
            
            livro = new Livro();
            
            livro.setNome(tfNome.getText());
            livro.setAutor(tfAutor.getText());
            livro.setQtdPaginas(Integer.parseInt(tfQtdPaginas.getText()));
            livro.setAnoLancamento(Integer.parseInt(tfAnoLancamento.getText()));
            livro.setGenero(tfGenero.getText());
            
            if(tfCodigo.getText().equals("")){ //verifica se jã existe um id
                //caso não haja, insere um novo registro
                daoLivro.inserir(livro);
            }else{
                livro.setId(Integer.parseInt(tfCodigo.getText()));
                daoLivro.alterar(livro);
            }
            
            limparCampos();
            atualizarTabelaLivros();
        }
        
         
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jTableLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLivroMouseClicked
        // método que popula todos os campos de cadastro com dados
        // de um livro já cadastrado no sistema quando clicado no registro
        
        tfCodigo.setText(jTableLivro.getValueAt(
                             jTableLivro.getSelectedRow(), 
                             LivroTableModel.COL_CODIGO).toString());
        tfNome.setText(jTableLivro.getValueAt(
                           jTableLivro.getSelectedRow(), 
                           LivroTableModel.COL_NOME).toString());
        tfAutor.setText(jTableLivro.getValueAt(
                            jTableLivro.getSelectedRow(), 
                            LivroTableModel.COL_AUTOR).toString());
        tfQtdPaginas.setText(jTableLivro.getValueAt(
                                 jTableLivro.getSelectedRow(), 
                                 LivroTableModel.COL_PAGINAS).toString());
        tfAnoLancamento.setText(jTableLivro.getValueAt(
                                    jTableLivro.getSelectedRow(), 
                                    LivroTableModel.COL_LANCAMENTO).toString());
        tfGenero.setText(jTableLivro.getValueAt(
                             jTableLivro.getSelectedRow(), 
                             LivroTableModel.COL_GENERO).toString());
    }//GEN-LAST:event_jTableLivroMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, 
                "Confirma a exclusão do livro com o código " + tfCodigo.getText() + "?", 
                "Exclusão de livro",
                JOptionPane.YES_NO_OPTION);
        
        if(confirm == 0){
            daoLivro.excluir(Integer.parseInt(tfCodigo.getText()));
            limparCampos();
            atualizarTabelaLivros();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        // Quando o botão "filtrar" for clicado,
        // define o campo o qual foi selecionado no radios button
        // e filtra a lista  a partir disso
        String campo = "";
        
        if(rbGenero.isSelected()){
            campo = "genero";
        }else if(rbAutor.isSelected()){
            campo = "autor";
        }else{
            campo = "nome";
        }
        
        jTableLivro.setModel(new LivroTableModel(daoLivro.filtrar(campo, tfFiltro.getText())));
        limparCampos();
    }//GEN-LAST:event_btnFiltroActionPerformed

    private void btnListaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaTodosActionPerformed
        limparCampos();
        tfFiltro.setText("");
        atualizarTabelaLivros();
    }//GEN-LAST:event_btnListaTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LivroView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFiltro;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnListaTodos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivro;
    private javax.swing.JLabel labelAnoLancamento;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelFiltro;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelQtdPaginas;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JRadioButton rbAutor;
    private javax.swing.JRadioButton rbGenero;
    private javax.swing.JRadioButton rbTitulo;
    private javax.swing.JTextField tfAnoLancamento;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfFiltro;
    private javax.swing.JTextField tfGenero;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfQtdPaginas;
    // End of variables declaration//GEN-END:variables
}
